server:
  port: 8085

spring:
  application:
    name: coupon-service
  datasource:
    url: jdbc:mysql://localhost:3306/userservice?useSSL=false
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  flyway:
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
