server:
  servlet:
    context-path: /admin-services
  port: 8081



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/playground?useSSL=false
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  flyway:
    baseline-on-migrate: true

